services:
  - type: web
    name: uazapi-helper
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: UAZAPI_BASE_URL
        value: https://onnzetecnologia.uazapi.com
      - key: UAZAPI_INSTANCE_NAME
        value: RTEPORT_INSTANTANEO
      - key: UAZAPI_TOKEN
        sync: false
